[env]
LC_CTYPE = "en_US.UTF-8"
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "SemiBold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[shell]
program = "ubuntu"

# Shift bindings
[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"
