[env]
LC_CTYPE = "en_US.UTF-8"
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "SemiBold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[shell]
program = "C:/msys64/msys2_shell.cmd"
args = ["-defterm", "-no-start", "-use-full-path", "-clang64", "-here", "-shell", "zsh"]

# Shift bindings
# Prevents inserting newline while holding shift.
# [[keyboard.bindings]]
# chars = "\u001B[13;2u"
# key = "Return"
# mods = "Shift"

# [keyboard]
# bindings = [
#     { key= "Minus", mods = "Alt", chars = "\\x1b_"                       },
# ]

# [[keyboard.bindings]]
# chars = "\u001B[43;3u"
# key = "Plus"
# mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[104;3u"
key = "h"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[72;4u"
key = "H"
mods = "Alt|Shift"

# TODO: Figure out way to bind to alt key.
[[keyboard.bindings]]
chars = "\u001B[61;5u"
key = "="
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[45;5u"
key = "-"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[44;5u"
key = ","
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[46;5u"
key = "."
mods = "Control"

# [[keyboard.bindings]]
# chars = "\\x1b-"
# key = "Minus"
# mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[9;5u"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[9;6u"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[47;5u"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[72;5u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[74;5u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;5u"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;5u"
key = "L"
mods = "Control|Shift"


# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'

green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
