require("globals.globals")
require("globals.globals-nvim-tree")
require("options.options")
require("options.options-colortheme")
require("keymaps.keymaps")
require("keymaps.keymaps-buffers")
require("plugin-manager")
