require("globals.globals")
require("globals.globals-nvim-tree")
require("options.options")
require("options.colortheme")
require("options.indentation")
require("options.wrapping")
if vim.fn.has("win32") or vim.fn.has("win64") then
    require("options.msys")
end
require("keymaps.keymaps")
require("keymaps.keymaps-comments")
require("keymaps.keymaps-buffers")
require("keymaps.keymaps-movements")
require("keymaps.keymaps-windows")
require("keymaps.keymaps-terminal")
require("keymaps.keymaps-tabs")
require("plugin-manager")
