vim.keymap.set("n", "<Leader>1", "1gt", { noremap = true, silent = true })
vim.keymap.set("n", "<Leader>2", "2gt", { noremap = true, silent = true })
vim.keymap.set("n", "<Leader>3", "3gt", { noremap = true, silent = true })
vim.keymap.set("n", "<Leader>4", "4gt", { noremap = true, silent = true })
vim.keymap.set("n", "<Leader>5", "5gt", { noremap = true, silent = true })
