vim.keymap.set({ "n", "v", "i" }, "<C-j>", function()
    vim.cmd("norm! 15j")
end, { noremap = true, silent = true })
vim.keymap.set({ "n", "v", "i" }, "<C-k>", function()
    vim.cmd("norm! 15k")
end, { noremap = true, silent = true })
vim.keymap.set({ "n", "v", "i" }, "<C-h>", function()
    vim.cmd("norm! 15h")
end, { noremap = true, silent = true })
vim.keymap.set({ "n", "v", "i" }, "<C-l>", function()
    vim.cmd("norm! 15l")
end, { noremap = true, silent = true })

vim.keymap.set({ "n", "v", "i" }, "<C-S-h>", function()
    vim.cmd("norm! ^")
end, { noremap = true, silent = true })
vim.keymap.set({ "n", "v", "i" }, "<C-S-l>", function()
    vim.cmd("norm! $")
end, { noremap = true, silent = true })
