vim.keymap.set({ "n", "v" }, "<C-=>", "2<C-w>+", { noremap = true, silent = true })
vim.keymap.set({ "n", "v" }, "<C--->", "2<C-w>-", { noremap = true, silent = true })
vim.keymap.set({ "n", "v" }, "<C-,>", "2<C-w><", { noremap = true, silent = true })
vim.keymap.set({ "n", "v" }, "<C-.>", "2<C-w>>", { noremap = true, silent = true })
vim.keymap.set({ "n", "v" }, "<C-S-q>", "<Cmd>q<CR>", { noremap = true, silent = true })
